version: "3.8"

services:
  bot:
    build: .

    environment:
      TOKEN: file:/run/secrets/token
      PREFIX: str:-

      GUILD_ID: int:626608699942764544

      STDOUT_CHANNEL_ID: int:711367399399620691
      MAIL_CHANNEL_ID: int:700101707727634452

    secrets:
      - token

secrets:
  token:
    file: ./secrets/token
